language: python
python:
  - "2.7"
addons:
  postgresql: "9.3"
services: postgresql
env:
  - DATABASE_URL="postgres://postgres@localhost/braindump"
install: "pip install -r requirements.txt"
script: "python manage.py test"
