language: python
python:
  - "2.7"
services: postgres
env: DATABASE_URL = "postgres://postgres@localhost/braindump"
install: "pip install -r requirements.txt"
before_script:
  - "psql -c 'create database braindump;' -U postgres"
script: "python manage.py test"
