from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'', include(include('api.urls'))),
                       url(r'^$', TemplateView.as_view(template_name="index.html"), name='home'),
)

if settings.DEBUG:
    # special case as the main.css is generated by compass in a tmp dir
    urlpatterns += static('/styles/', document_root='client/.tmp/styles')
