from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import os

admin.autodiscover()

urlpatterns = patterns('',
                       # REST API
                       url(r'', include('api.urls')),

                       # admin interface
                       url(r'^admin/', include(admin.site.urls)),

                       # root files
                       url(r'^(?P<path>favicon\.ico|apple-touch-icon\.png)$',
                           'django.views.static.serve',
                           kwargs={'document_root': os.path.join(settings.BASE_DIR, 'root')}),

                       url(r'', include('brainstorming.urls'))
)

if settings.DEBUG:
    # special case as the main.css is generated by compass in a tmp dir
    urlpatterns += static('/styles/', document_root='client/.tmp/styles')
